name: dynamic_cached_fonts
description: A font loader to download, cache and load web fonts in flutter with support for Firebase Cloud Storage.
version: 1.0.0
repository: https://github.com/sidrao2006/dynamic_cached_fonts

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_storage: 11.7.6
  flutter_cache_manager: 3.3.2
  meta: 1.15.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.4

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/GoogleService-Info.plist
  - /example/macos/GoogleService-Info.plist
  - /example/web/index.html
